const KEY='engineering-notebook-v1';let data=load(),chapterId=null,sectionId=null,pendingDelete=null;const $=s=>document.querySelector(s),uid=()=>crypto.randomUUID();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{title:'My Engineering Notebook',chapters:[]}}catch{return{title:'My Engineering Notebook',chapters:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));$('#status').textContent='Saved locally';renderTree()}
function find(nodes,id){for(const n of nodes){if(n.id===id)return n;const x=find(n.children,id);if(x)return x}}
function map(nodes,id,fn){return nodes.map(n=>n.id===id?fn(n):Object.assign({},n,{children:map(n.children,id,fn)}))}
function remove(nodes,id){return nodes.filter(n=>n.id!==id).map(n=>Object.assign({},n,{children:remove(n.children,id)}))}
function numberOf(nodes,id,p){for(let i=0;i<nodes.length;i++){const x=p+'.'+(i+1);if(nodes[i].id===id)return x;const y=numberOf(nodes[i].children,id,x);if(y)return y}}
function currentChapter(){return data.chapters.find(c=>c.id===chapterId)}function currentSection(){return currentChapter()&&find(currentChapter().sections,sectionId)}
function esc(x){return String(x).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function addChapter(){const c={id:uid(),title:'Untitled chapter',sections:[],open:true};data.chapters.push(c);chapterId=c.id;sectionId=null;save();show()}
function addSection(parent){const c=currentChapter();if(!c)return;const s={id:uid(),title:parent?'Untitled subsection':'Untitled section',content:'',children:[],open:true};c.sections=parent?map(c.sections,parent,p=>Object.assign({},p,{children:p.children.concat(s),open:true})):c.sections.concat(s);sectionId=s.id;c.open=true;save();show()}
function sectionRows(nodes,p,d){d=d||0;return nodes.map((s,i)=>{const n=p+'.'+(i+1),kids=s.children.length;return '<div><div class="tree-row '+(sectionId===s.id?'active':'')+'" style="padding-left:'+(d*14)+'px"><button class="toggle" data-toggle="'+s.id+'">'+(kids?(s.open?'▾':'▸'):'')+'</button><button class="label" data-section="'+s.id+'"><span>'+n+'</span>'+esc(s.title)+'</button></div>'+(s.open?sectionRows(s.children,n,d+1):'')+'</div>'}).join('')}
function renderTree(){$('#tree').innerHTML=data.chapters.map((c,i)=>'<div><div class="tree-row '+(chapterId===c.id&&!sectionId?'active':'')+'"><button class="toggle" data-chapter-toggle="'+c.id+'">'+(c.open?'▾':'▸')+'</button><button class="label" data-chapter="'+c.id+'"><span>'+(i+1)+'</span>'+esc(c.title)+'</button></div>'+(c.open?sectionRows(c.sections,String(i+1),0)+'<button class="label" data-add-section="'+c.id+'">＋ Add section</button>':'')+'</div>').join('')}
function show(){const c=currentChapter(),s=currentSection();$('#welcome').hidden=!!c;$('#chapter-view').hidden=!c||!!s;$('#section-view').hidden=!s;if(c&&!s){const i=data.chapters.indexOf(c)+1;$('#chapter-view').innerHTML='<small>CHAPTER '+i+'</small><input class="chapter-title" value="'+esc(c.title)+'"><div class="chapter-actions"><button class="primary" id="new-section">＋ Add section</button><button id="pdf-chapter">Export chapter PDF</button><button class="danger" id="remove-chapter">Delete</button></div><p>'+c.sections.length+' top-level sections</p>';$('#new-section').onclick=()=>addSection();$('#pdf-chapter').onclick=()=>printChapter(c,i);$('#remove-chapter').onclick=()=>askDelete('chapter',c.id);$('.chapter-title').oninput=e=>{c.title=e.target.value;save()}}if(s){$('#section-number').textContent='SECTION '+numberOf(c.sections,s.id,String(data.chapters.indexOf(c)+1));$('#section-title').value=s.title;$('#editor').innerHTML=s.content||''}renderTree()}
function sectionHtml(s,n){return '<section><h2>'+n+' '+esc(s.title)+'</h2>'+s.content+s.children.map((x,i)=>sectionHtml(x,n+'.'+(i+1))).join('')+'</section>'}
function printDoc(title,body){const w=open('','_blank');if(!w)return alert('Allow pop-ups to create a PDF.');w.document.write('<!doctype html><title>'+esc(title)+'</title><style>@page{margin:22mm}body{font:16px/1.65 Georgia;max-width:800px;margin:auto;color:#172033}h1,h2{font-family:Arial}h1{border-bottom:2px solid #174f78;padding-bottom:12px}blockquote{border-left:4px solid #aac4d6;padding-left:18px}</style><h1>'+esc(title)+'</h1>'+body);w.document.close();setTimeout(()=>w.print(),200)}
function printChapter(c,i){printDoc(i+' '+c.title,c.sections.map((s,x)=>sectionHtml(s,i+'.'+(x+1))).join(''))}
function askDelete(kind,id){pendingDelete={kind,id};$('#confirm').showModal()}
$('#book-title').value=data.title;$('#book-title').oninput=e=>{data.title=e.target.value;save()};$('#add-chapter').onclick=$('#first-chapter').onclick=addChapter;$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');
$('#tree').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.chapter){chapterId=b.dataset.chapter;sectionId=null;show()}if(b.dataset.section){sectionId=b.dataset.section;show()}if(b.dataset.addSection){chapterId=b.dataset.addSection;addSection()}if(b.dataset.chapterToggle){const c=data.chapters.find(x=>x.id===b.dataset.chapterToggle);c.open=!c.open;save()}if(b.dataset.toggle){const c=currentChapter();c.sections=map(c.sections,b.dataset.toggle,s=>Object.assign({},s,{open:!s.open}));save()}$('#sidebar').classList.remove('open')};
$('#section-title').oninput=e=>{const c=currentChapter();c.sections=map(c.sections,sectionId,s=>Object.assign({},s,{title:e.target.value}));save()};$('#editor').oninput=e=>{const c=currentChapter();c.sections=map(c.sections,sectionId,s=>Object.assign({},s,{content:e.target.innerHTML}));save()};$('#add-subsection').onclick=()=>addSection(sectionId);$('#pdf-section').onclick=()=>{const s=currentSection(),n=numberOf(currentChapter().sections,s.id,String(data.chapters.indexOf(currentChapter())+1));printDoc(n+' '+s.title,s.content+s.children.map((x,i)=>sectionHtml(x,n+'.'+(i+1))).join(''))};$('#delete-section').onclick=()=>askDelete('section',sectionId);
$('#toolbar').onmousedown=e=>{const b=e.target.closest('[data-cmd]');if(b){e.preventDefault();document.execCommand(b.dataset.cmd);$('#editor').dispatchEvent(new Event('input'))}};$('#format').onchange=e=>document.execCommand('formatBlock',false,e.target.value);$('#text-color').oninput=e=>document.execCommand('foreColor',false,e.target.value);$('#highlight-color').oninput=e=>document.execCommand('hiliteColor',false,e.target.value);
$('#cancel-delete').onclick=()=>$('#confirm').close();$('#confirm-delete').onclick=()=>{if(pendingDelete.kind==='chapter'){data.chapters=data.chapters.filter(c=>c.id!==pendingDelete.id);chapterId=sectionId=null}else{const c=currentChapter();c.sections=remove(c.sections,pendingDelete.id);sectionId=null}$('#confirm').close();save();show()};
$('#export-backup').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='engineering-notebook-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#import-backup').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.chapters))throw Error();data=x;chapterId=sectionId=null;$('#book-title').value=data.title;save();show()}catch{alert('This is not a valid notebook backup.')}};r.readAsText(f)};
renderTree();show();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
